### ISSUE TITLE
Highlight the first two options

### ISSUE THREAD

**Issue by basilkar** [RheaMars/eu-indentation-converter#3]
The first two options being the ones that are due to the ambiguity of _the last_ `z`.

For example:
```
12zza:
1. 12.zza <-
2. 12.z.za
3. 12.zz.a <-
4. 12.z.z.a
```

**Comment by RheaMars** [comment]
Frontend for the changes is prepared in draft PR: https://github.com/RheaMars/eu-indentation-converter/pull/23
